name: integration-test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 19

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Integration Test
        run: ./gradlew projects clean integrationTest --no-daemon --refresh-dependencies

      - name: Upload coverage to Codecov (Linux only)
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          flags: integration-tests
          fail_ci_if_error: true
