name: release

on:
  workflow_run:
    workflows: [ build ]
    types: [ completed ]
    branches: [ main ]

permissions:
  contents: write
  statuses: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # need this because workflow_run doesn't set the status otherwise
      - name: Set pending commit status
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: pending

      - name: Bump version
        id: version
        uses: paulhatch/semantic-version@v5.4.0

      - name: Create GitHub tag and release
        uses: softprops/action-gh-release@v2.0.5
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          generate_release_notes: true

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@v2.0.1
        if: always()
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          status: ${{ job.status }}
